### ISSUE TITLE
Error: cannot use tv.Sec (variable of type int32) as int64 value in return statement

### ISSUE THREAD

**Issue by healthcareguy** [GoWebProd/uuid7#1]
Unable to run example, getting error:

`go\pkg\mod\github.com\!go!web!prod\gip@v0.0.0-20220218143836-6b4b6eb4f24c\fasttime\fasttime.go:170:9: cannot use tv.Sec (variable of type int32) as int64 value in return statement`

Using `go version go1.20.4 windows/amd64`

**Comment by GoWebProd** [comment]
Hello. Thank you for report. Can you try with new version?

**Comment by healthcareguy** [comment]
Updated and also updated go to `go version go1.20.5 windows/amd64`. Works!
